on:
    push:
      # Sequence of patterns matched against refs/tags
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  
name: Create RPM Release

jobs:
    build:
        name: Create RPM Release
        runs-on: ubuntu-latest

        steps:

        - name: Checkout code
          uses: actions/checkout@v2

            
        - name: build RPM package
          id: rpm_build
          uses: ianabc/github-action-rpmbuild@v0.1.1

        - name: Upload Release Assets
          run: |
              set -x
              assets=()
              for asset in ${GITHUB_WORKSPACE}/SRPMS/*.src.rpm; do
                  assets+=("-a" "${asset}")
              done
              for asset in ${GITHUB_WORKSPACE}/RPMS/noarch/*.rpm; do
                  assets+=("-a" "${asset}")
              done
              for asset in ${GITHUB_WORKSPACE}/RPMS/x86_64/*.rpm; do
                  assets+=("-a" "${asset}")
              done
              tag_name="${GITHUB_REF##*/}"
              hub release create "${assets[@]}" -m "${tag_name}" "${tag_name}"
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
